# Nombre de tu proyecto
spring.application.name=Gestion_biblioteca

# Configuración de Base de Datos en Memoria (H2)
spring.datasource.url=jdbc:h2:mem:bibliotecaDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola para mostrarle al profe las tablas en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate: Crea las tablas automáticamente al arrancar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true